# Copyright (c) 2024 Project CHIP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build_overrides/build.gni")
import("//build_overrides/chip.gni")
import("//build_overrides/pigweed.gni")
import(
    "//src/python_testing/matter_testing_infrastructure/credential_files.gni")
import("//src/python_testing/matter_testing_infrastructure/data_model_xmls.gni")
import("$dir_pw_build/python.gni")
import("$dir_pw_build/python_dist.gni")
import("$dir_pw_build/zip.gni")

pw_python_package("matter-testing-module") {
  generate_setup = {
    metadata = {
      name = "matter-testing-module"
      version = "1.4.0"
      description = "Testing support for Matter SDK"
      url = "https://github.com/project-chip/connectedhomeip"
      classifiers = [
        "Intended Audience :: Developers",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python :: 3",
      ]
    }
  }

  inputs = [ "env_test.yaml" ]

  sources = [
    "matter/testing/CommissioningPreTest.py",
    "matter/testing/TestTimeSyncTrustedTimeSourceRunner.py",
    "matter/testing/__init__.py",
    "matter/testing/apps.py",
    "matter/testing/basic_composition.py",
    "matter/testing/chiptest/__init__.py",
    "matter/testing/chiptest/accessories.py",
    "matter/testing/chiptest/concurrency/__init__.py",
    "matter/testing/chiptest/concurrency/context.py",
    "matter/testing/chiptest/concurrency/process.py",
    "matter/testing/chiptest/concurrency/work_queue.py",
    "matter/testing/chiptest/darwin.py",
    "matter/testing/chiptest/glob_matcher.py",
    "matter/testing/chiptest/linux/__init__.py",
    "matter/testing/chiptest/linux/bluetooth.py",
    "matter/testing/chiptest/linux/dbus.py",
    "matter/testing/chiptest/linux/namespace.py",
    "matter/testing/chiptest/linux/thread.py",
    "matter/testing/chiptest/linux/wifi.py",
    "matter/testing/chiptest/log_config.py",
    "matter/testing/chiptest/results.py",
    "matter/testing/chiptest/runner.py",
    "matter/testing/chiptest/status.py",
    "matter/testing/chiptest/test_definition.py",
    "matter/testing/chiptest/worker.py",
    "matter/testing/chiptest/yamltest_with_matter_repl_tester.py",
    "matter/testing/chipyaml/__init__.py",
    "matter/testing/chipyaml/adapters/__init__.py",
    "matter/testing/chipyaml/adapters/chiptool/__init__.py",
    "matter/testing/chipyaml/adapters/chiptool/adapter.py",
    "matter/testing/chipyaml/adapters/chiptool/decoder.py",
    "matter/testing/chipyaml/adapters/chiptool/encoder.py",
    "matter/testing/chipyaml/adapters/placeholder/__init__.py",
    "matter/testing/chipyaml/adapters/placeholder/adapter.py",
    "matter/testing/chipyaml/adapters/repl/__init__.py",
    "matter/testing/chipyaml/adapters/repl/adapter.py",
    "matter/testing/chipyaml/adapters/repl/runner.py",
    "matter/testing/chipyaml/chiptool.py",
    "matter/testing/chipyaml/darwinframeworktool.py",
    "matter/testing/chipyaml/extensions/__init__.py",
    "matter/testing/chipyaml/extensions/example_cluster.py",
    "matter/testing/chipyaml/extensions/wildcard_response_extractor_cluster.py",
    "matter/testing/chipyaml/paths_finder.py",
    "matter/testing/chipyaml/runner.py",
    "matter/testing/chipyaml/tests_finder.py",
    "matter/testing/chipyaml/tests_logger.py",
    "matter/testing/chipyaml/tests_tool.py",
    "matter/testing/choice_conformance.py",
    "matter/testing/commissioning.py",
    "matter/testing/commissioning_types.py",
    "matter/testing/conformance.py",
    "matter/testing/conversions.py",
    "matter/testing/credentials.py",
    "matter/testing/decorators.py",
    "matter/testing/default_checker.py",
    "matter/testing/defaults.py",
    "matter/testing/device_conformance_tests.py",
    "matter/testing/event_attribute_reporting.py",
    "matter/testing/generate_data_model_xmls_gni.py",
    "matter/testing/global_attribute_ids.py",
    "matter/testing/global_stash.py",
    "matter/testing/java/base.py",
    "matter/testing/java/bdx_test.py",
    "matter/testing/java/commissioning_test.py",
    "matter/testing/java/discover_test.py",
    "matter/testing/java/im_test.py",
    "matter/testing/java/ota_test.py",
    "matter/testing/linux/log_line_processing.py",
    "matter/testing/linux/tv_casting_test_sequence_utils.py",
    "matter/testing/linux/tv_casting_test_sequences.py",
    "matter/testing/local.py",
    "matter/testing/matchers.py",
    "matter/testing/matter_asserts.py",
    "matter/testing/matter_stack_state.py",
    "matter/testing/matter_test_config.py",
    "matter/testing/matter_testing.py",
    "matter/testing/matter_yaml_linter.py",
    "matter/testing/metadata.py",
    "matter/testing/nfc.py",
    "matter/testing/pics.py",
    "matter/testing/problem_notices.py",
    "matter/testing/run_darwin_framework_ota_test.py",
    "matter/testing/run_fuzztest_coverage.py",
    "matter/testing/run_java_test.py",
    "matter/testing/run_kotlin_test.py",
    "matter/testing/run_python_test.py",
    "matter/testing/run_test_suite.py",
    "matter/testing/run_tv_casting_test.py",
    "matter/testing/runner.py",
    "matter/testing/spec_parsing.py",
    "matter/testing/step_extractor.py",
    "matter/testing/taglist_and_topology_test.py",
    "matter/testing/tasks.py",
    "matter/testing/timeoperations.py",
  ]
  tests = [
    "matter/testing/test_metadata.py",
    "matter/testing/test_tasks.py",
    "matter/testing/test_matter_asserts.py",
  ]
}

pw_zip("data_model_zip_1_1") {
  inputs = []
  foreach(file, data_model_XMLS_1_1) {
    zip_path = rebase_path(file, "${chip_root}/data_model/1.1/", "/")
    inputs += [ "${file} > /${zip_path}" ]
  }
  output = "${root_out_dir}/data_model/zip_1_1.zip"
}

pw_zip("data_model_zip_1_2") {
  inputs = []
  foreach(file, data_model_XMLS_1_2) {
    zip_path = rebase_path(file, "${chip_root}/data_model/1.2/", "/")
    inputs += [ "${file} > /${zip_path}" ]
  }
  output = "${root_out_dir}/data_model/zip_1_2.zip"
}

pw_zip("data_model_zip_1_3") {
  inputs = []
  foreach(file, data_model_XMLS_1_3) {
    zip_path = rebase_path(file, "${chip_root}/data_model/1.3/", "/")
    inputs += [ "${file} > /${zip_path}" ]
  }
  output = "${root_out_dir}/data_model/zip_1_3.zip"
}

pw_zip("data_model_zip_1_4") {
  inputs = []
  foreach(file, data_model_XMLS_1_4) {
    zip_path = rebase_path(file, "${chip_root}/data_model/1.4/", "/")
    inputs += [ "${file} > /${zip_path}" ]
  }
  output = "${root_out_dir}/data_model/zip_1_4.zip"
}

pw_zip("data_model_zip_1_4_1") {
  inputs = []
  foreach(file, data_model_XMLS_1_4_1) {
    zip_path = rebase_path(file, "${chip_root}/data_model/1.4.1/", "/")
    inputs += [ "${file} > /${zip_path}" ]
  }
  output = "${root_out_dir}/data_model/zip_1_4_1.zip"
}

pw_zip("data_model_zip_1_4_2") {
  inputs = []
  foreach(file, data_model_XMLS_1_4_2) {
    zip_path = rebase_path(file, "${chip_root}/data_model/1.4.2/", "/")
    inputs += [ "${file} > /${zip_path}" ]
  }
  output = "${root_out_dir}/data_model/zip_1_4_2.zip"
}

pw_zip("data_model_zip_1_5") {
  inputs = []
  foreach(file, data_model_XMLS_1_5) {
    zip_path = rebase_path(file, "${chip_root}/data_model/1.5/", "/")
    inputs += [ "${file} > /${zip_path}" ]
  }
  output = "${root_out_dir}/data_model/zip_1_5.zip"
}

pw_zip("data_model_zip_1_5_1") {
  inputs = []
  foreach(file, data_model_XMLS_1_5_1) {
    zip_path = rebase_path(file, "${chip_root}/data_model/1.5.1/", "/")
    inputs += [ "${file} > /${zip_path}" ]
  }
  output = "${root_out_dir}/data_model/zip_1_5_1.zip"
}

pw_zip("data_model_zip_1_6") {
  inputs = []
  foreach(file, data_model_XMLS_1_6) {
    zip_path = rebase_path(file, "${chip_root}/data_model/1.6/", "/")
    inputs += [ "${file} > /${zip_path}" ]
  }
  output = "${root_out_dir}/data_model/zip_1_6.zip"
}

pw_zip("credential_zip_development") {
  inputs = []
  foreach(file, credentials_development) {
    zip_path = rebase_path(file, "${chip_root}/credentials/development/", "/")
    inputs += [ "${file} > /${zip_path}" ]
  }
  output = "${root_out_dir}/credentials/zip_development.zip"
}

pw_zip("credential_zip_production") {
  inputs = []
  foreach(file, credentials_production) {
    zip_path = rebase_path(file, "${chip_root}/credentials/production/", "/")
    inputs += [ "${file} > /${zip_path}" ]
  }
  output = "${root_out_dir}/credentials/zip_production.zip"
}

pw_python_distribution("matter-testing") {
  packages = [ ":matter-testing-module" ]

  generate_setup_cfg = {
    name = "matter-testing"
    version = "1.4.2"
    include_default_pyproject_file = true
    include_extra_files_in_package_data = true
  }

  public_deps = [
    ":credential_zip_development",
    ":credential_zip_production",
    ":data_model_zip_1_1",
    ":data_model_zip_1_2",
    ":data_model_zip_1_3",
    ":data_model_zip_1_4",
    ":data_model_zip_1_4_1",
    ":data_model_zip_1_4_2",
    ":data_model_zip_1_5",
    ":data_model_zip_1_5_1",
    ":data_model_zip_1_6",
  ]

  extra_files = [
    "${root_out_dir}/data_model/zip_1_1.zip > matter/testing/data_model/1.1/allfiles.zip",
    "${root_out_dir}/data_model/zip_1_2.zip > matter/testing/data_model/1.2/allfiles.zip",
    "${root_out_dir}/data_model/zip_1_3.zip > matter/testing/data_model/1.3/allfiles.zip",
    "${root_out_dir}/data_model/zip_1_4.zip > matter/testing/data_model/1.4/allfiles.zip",
    "${root_out_dir}/data_model/zip_1_4_1.zip > matter/testing/data_model/1.4.1/allfiles.zip",
    "${root_out_dir}/data_model/zip_1_4_2.zip > matter/testing/data_model/1.4.2/allfiles.zip",
    "${root_out_dir}/data_model/zip_1_5.zip > matter/testing/data_model/1.5/allfiles.zip",
    "${root_out_dir}/data_model/zip_1_5_1.zip > matter/testing/data_model/1.5.1/allfiles.zip",
    "${root_out_dir}/data_model/zip_1_6.zip > matter/testing/data_model/1.6/allfiles.zip",
    "${root_out_dir}/credentials/zip_development.zip > matter/testing/credentials/development/allfiles.zip",
    "${root_out_dir}/credentials/zip_production.zip > matter/testing/credentials/production/allfiles.zip",
  ]
}
